/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oracleconnect;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hardy
 */
public class MainScreen extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }
    
    public void Refresh(){
         try{
             
          // POPULATE THE TABLE
          conn = ConnectDB.Connect();
          ps = conn.prepareStatement("SELECT * FROM hr.vw_employees ORDER BY employee_id");
          rs = ps.executeQuery();
          tblEmployees.setModel(DbUtils.resultSetToTableModel(rs));  
          
          
          // POPULATE COMBO BOX JOB ID 
          ps = conn.prepareStatement("SELECT JOB_TITLE FROM HR.JOBS ORDER BY JOB_ID");
          rs = ps.executeQuery();
          
          while(rs.next())
          {
              cmbJobID.addItem(rs.getString("JOB_TITLE"));
          }
          
          // POPULATE COMBO BOX MANAGER ID
          ps = conn.prepareStatement("SELECT LAST_NAME || ', ' || FIRST_NAME AS MANAGER_NAME FROM HR.EMPLOYEES ORDER BY LAST_NAME");
          rs = ps.executeQuery();
          
          while(rs.next())
          {
              cmbManagerID.addItem(rs.getString("MANAGER_NAME"));
          }
          
          // POPULATE COMBO BOX DEPARTMENT ID
          ps = conn.prepareStatement("SELECT DEPARTMENT_NAME FROM HR.DEPARTMENTS ORDER BY DEPARTMENT_NAME");
          rs = ps.executeQuery();
          while(rs.next())
          {
              cmbDepartmentID.addItem(rs.getString("DEPARTMENT_NAME"));
          }
         
          
        } catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmployeeNo = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtCommission = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbJobID = new javax.swing.JComboBox<>();
        cmbManagerID = new javax.swing.JComboBox<>();
        cmbDepartmentID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE RECORDS");
        setBackground(java.awt.SystemColor.controlDkShadow);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblEmployees.setBackground(javax.swing.UIManager.getDefaults().getColor("ViewTab.background"));
        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployees.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jLabel1.setText("Employee Number:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email Address:");

        btnAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        jLabel4.setText("Phone Number:");

        jLabel5.setText("First Name:");

        jLabel6.setText("Salary:");

        jLabel7.setText("Commission Percent:");

        jLabel8.setText("Manager ID:");

        jLabel9.setText("Department ID:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        jLabel10.setText("Job Title");

        cmbJobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJobIDActionPerformed(evt);
            }
        });

        cmbManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbManagerIDActionPerformed(evt);
            }
        });

        cmbDepartmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtEmployeeNo)
                            .addComponent(txtFirstName)
                            .addComponent(cmbManagerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDepartmentID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtSalary)
                                    .addComponent(txtEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCommission)
                                    .addComponent(cmbJobID, 0, 216, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJobID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     Refresh();     
    }//GEN-LAST:event_formWindowActivated

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        
        int respond = JOptionPane.showConfirmDialog(null, "Confirm Adding?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (respond == JOptionPane.YES_OPTION){
        try {
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(
                    "INSERT INTO HR.EMPLOYEES "
                    + "(employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, commission_pct, manager_id, department_id) "
                    + "VALUES ('" + txtEmployeeNo.getText().trim() + "', '"
                    + txtFirstName.getText().trim() + "', '"
                    + txtLastName.getText().trim() + "', '"
                    + txtEmail.getText().trim() + "', '"
                    + txtPhoneNum.getText().trim() + "', '"
                    + "1/09/2025', "
                    + "(SELECT job_id FROM HR.JOBS WHERE job_title = '" + cmbJobID.getSelectedItem().toString().trim() + "'), '"
                    + txtSalary.getText().trim() + "', '"
                    + txtCommission.getText().trim() + "', "
                    + "(SELECT employee_id FROM HR.EMPLOYEES WHERE last_name || ', ' || first_name = '" + cmbManagerID.getSelectedItem().toString().trim() + "'), "
                    + "(SELECT department_id FROM HR.DEPARTMENTS WHERE department_name = '" + cmbDepartmentID.getSelectedItem().toString().trim() + "'))"
                ); 
            
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Record Added.");
                Refresh();
                
            } catch(Exception e){
                System.out.println(e);
            }
        } // YES
        else 
            JOptionPane.showMessageDialog(null, "Adding Cancelled.");

    }//GEN-LAST:event_btnAddMouseClicked

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        // TODO add your handling code here:
        
        // clicking the table
        
        int row = tblEmployees.getSelectedRow();
        txtEmployeeNo.setText(tblEmployees.getModel().getValueAt(row, 0).toString());
        txtFirstName.setText(tblEmployees.getModel().getValueAt(row, 2).toString());
        txtLastName.setText(tblEmployees.getModel().getValueAt(row, 1).toString());
        txtEmail.setText(tblEmployees.getModel().getValueAt(row, 3).toString());
        txtPhoneNum.setText(tblEmployees.getModel().getValueAt(row, 4).toString());
        txtSalary.setText(tblEmployees.getModel().getValueAt(row, 7).toString());
        txtCommission.setText(tblEmployees.getModel().getValueAt(row, 8).toString());
        cmbManagerID.setSelectedItem(tblEmployees.getModel().getValueAt(row, 9).toString());
        cmbDepartmentID.setSelectedItem(tblEmployees.getModel().getValueAt(row, 10).toString());
        cmbJobID.setSelectedItem(tblEmployees.getModel().getValueAt(row, 6).toString());

        
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        // UPDATE
        
        int respond = JOptionPane.showConfirmDialog(null, "Confirm Update?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (respond == JOptionPane.YES_OPTION){
        try{
            conn = ConnectDB.Connect();

                ps = conn.prepareStatement(
         "UPDATE HR.EMPLOYEES SET "
         + "first_name = '" + txtFirstName.getText().trim() + "', "
         + "last_name = '" + txtLastName.getText().trim() + "', "
         + "email = '" + txtEmail.getText().trim() + "', "
         + "phone_number = '" + txtPhoneNum.getText().trim() + "', "
         + "salary = '" + txtSalary.getText().trim() + "', "
         + "commission_pct = '" + txtCommission.getText().trim() + "', "
         + "manager_id = (SELECT employee_id FROM HR.EMPLOYEES WHERE last_name || ', ' || first_name = '"
         + cmbManagerID.getSelectedItem().toString().trim() + "'), "
         + "department_id = (SELECT department_id FROM HR.DEPARTMENTS WHERE department_name = '"
         + cmbDepartmentID.getSelectedItem().toString().trim() + "'), "
         + "job_id = (SELECT job_id FROM HR.JOBS WHERE job_title = '"
         + cmbJobID.getSelectedItem().toString().trim() + "') "
         + "WHERE employee_id = '" + txtEmployeeNo.getText().trim() + "'"
     );

            ps.execute();
            Refresh();
            JOptionPane.showMessageDialog(null, "Record Updated.");
        } catch(Exception e){
            System.out.println(e);
            }

        } // YES
        else 
            JOptionPane.showMessageDialog(null, "Update Cancelled.");
        Refresh();
        
        
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here: // DELETE
        
        int respond = JOptionPane.showConfirmDialog(null, "Confirm Delete?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (respond == JOptionPane.YES_OPTION){
        try{
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement("DELETE FROM HR.EMPLOYEES WHERE employee_id = '"+txtEmployeeNo.getText().trim()+"' ");
            ps.execute();
            Refresh();
        } catch(Exception e){
            System.out.println(e);
            }
            JOptionPane.showMessageDialog(null, "Record Deleted.");
        } // YES
        else 
            JOptionPane.showMessageDialog(null, "Deletion Cancelled.");
          
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void cmbJobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJobIDActionPerformed
      Refresh();
    }//GEN-LAST:event_cmbJobIDActionPerformed

    private void cmbManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbManagerIDActionPerformed
        Refresh();
    }//GEN-LAST:event_cmbManagerIDActionPerformed

    private void cmbDepartmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentIDActionPerformed
        Refresh();
    }//GEN-LAST:event_cmbDepartmentIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDepartmentID;
    private javax.swing.JComboBox<String> cmbJobID;
    private javax.swing.JComboBox<String> cmbManagerID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtCommission;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
