
GRANT SELECT ON PLM_INFO_SYSTEM.STUDENT TO francis, jose, maria, josefa;

GRANT SELECT ON PLM_INFO_SYSTEM.EMPLOYEE TO maria, josefa;
GRANT SELECT ON PLM_INFO_SYSTEM.SUBJECT TO maria, josefa;

GRANT INSERT, UPDATE, DELETE ON PLM_INFO_SYSTEM.STUDENT TO francis, jose;
